// <auto-generated />
namespace websachs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class delete_table_Role : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(delete_table_Role));
        
        string IMigrationMetadata.Id
        {
            get { return "202011250936231_delete_table_Role"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
