// <auto-generated />
namespace websachs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update_table_User2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_table_User2));
        
        string IMigrationMetadata.Id
        {
            get { return "202011201028522_update_table_User2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
